### ISSUE TITLE
libs installed and threw excpetion when playing a video

### ISSUE THREAD

**Issue by zzeric** [linux-sunxi/libvdpau-sunxi#64]
I install the libs in a Orange Pi Plus (H3) with armbian , but when I play a video, threw a exception.

Here is my install steps, are there anything wrong?

1. sudo apt-get install libpixman-1-dev
2. sudo apt install libvdpau-dev
3. git clone https://github.com/linux-sunxi/libcedrus
   cd libcedrus
   sudo make && sudo make install
4. git clone https://github.com/linux-sunxi/libvdpau-sunxi, 
   cd libvdpau-sunxi
   sudo make && sudo make install
5. ldconfig
6. export VDPAU_DRIVER=sunxi
7. mpv --vo=vdpau --hwdec=vdpau --hwdec-codecs=all /home/zz/test.mp4

Playing: /home/zz/test.mp4
 (+) Video --vid=1 (*) (h264 1280x720 25.000fps)
 (+) Audio --aid=1 --alang=und (*) (aac 2ch 44100Hz)
[vo/vdpau] Error when calling vdp_device_create_x11: 25
Error opening/initializing the selected video_out (--vo) device.
Video: no video

**Comment by zzeric** [comment]
I upgraded pixman with latest source, then redo all the steps, the problem still keep the same

**Comment by zzeric** [comment]
Is it missing Mali driver? the vdpau error :25 seam related to driver

**Comment by rellla** [comment]
I see, http://linux-sunxi.org/Cedrus/libvdpau-sunxi is missing the hint, that libvdpau-sunxi only works with 3.4 legacy kernel, not with mainline. I suppose you are using mainline kernel and should therefore be missing /dev/cedar_dev. libvdpau_sunxi does not work with mainline kernel. 
Also, Mali has nothing to do with video decoding at all. http://linux-sunxi.org/Media_IP_cores

Because this issue seems to be not a problem of libvdpau_sunxi itself, i'm closing it so far.
